name: flutter_jaring_ummat
description: A new Flutter project.

version: 1.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera_utils: ^0.1.8
  jstomp: ^1.1.3
  bubble: ^1.1.9+1
  flushbar: ^1.8.2
  flutter_svg: ^0.13.1
  badges: ^1.1.0
  http: ^0.12.0+1
  shared_preferences: ^0.5.1+2
  image_picker: ^0.6.1+4
  cached_network_image: ^0.8.0
  video_player: ^0.10.0+2
  font_awesome_flutter: ^8.4.0
  mailer: ^3.0.1
  otp: ^1.0.1
  flutter_fab_dialer: ^0.1.1
  dio: ^2.1.13
  timeago: ^2.0.14
  flutter_money_formatter: ^0.8.0
  shimmer: ^1.0.0
  carousel_slider: ^1.3.0
  circular_profile_avatar: ^0.2.0
  pie_chart: ^0.9.0
  dots_indicator: ^0.0.5
  rubber: ^0.3.2
  toast: ^0.1.5
  flutter_bloc: ^0.17.0
  equatable: ^0.2.0
  camera: ^0.5.2+1
  story_view: ^0.9.1
  flutter_simple_video_player: ^0.0.9
  giffy_dialog: ^1.3.0
  fl_chart: ^0.1.2
  rxdart: ^0.22.0

  flutter_facebook_login:
    git: https://github.com/lequanghiep74/flutter_facebook_login

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ic_launcher/logo_mitra_jejaring.png"

flutter:
  uses-material-design: true

  fonts:
    - family:  Proxima
      fonts:
        - asset: assets/fonts/proxima_nova_soft.ttf

    - family:  Arab-Dances
      fonts:
        - asset: assets/fonts/ArabDances.ttf
  
    - family:  Sofia-Pro
      fonts:
        - asset: assets/fonts/Sofia-Pro-Black.ttf
        - asset: assets/fonts/Sofia-Pro-Bold.ttf
        - asset: assets/fonts/Sofia-Pro-ExtraLight.ttf
        - asset: assets/fonts/Sofia-Pro-Light.ttf

    - family:  HomePageIcons
      fonts:
        - asset: assets/fonts/HomePageIcons.ttf

    - family:  Navigation
      fonts:
        - asset: assets/fonts/Navigation.ttf
    
    - family:  SosialMedia
      fonts:
        - asset: assets/fonts/SosialMedia.ttf

    - family:  NewIcon
      fonts:
        - asset: assets/fonts/NewIcon.ttf

    - family:  AddIconInAmil
      fonts:
        - asset: assets/fonts/AddIconInAmil.ttf

    - family:  ActiveIcon
      fonts:
        - asset: assets/fonts/ActiveIcon.ttf


    - family:  CustomFonts 
      fonts:
        - asset: assets/fonts/custom_icons.ttf
        
    - family:  IconCustom 
      fonts:
        - asset: assets/fonts/IconCustom.ttf

    - family:  HeaderCustom 
      fonts:
        - asset: assets/fonts/HeaderCustom.ttf
     
    - family:  AppBarCustom
      fonts:
        - asset: assets/fonts/AppBarCustom.ttf

    - family:  NavbarCustom
      fonts:
        - asset: assets/fonts/NavbarCustom.ttf

    - family:  IconBaru
      fonts:
      - asset: assets/fonts/IconBaru.ttf

    - family:  MenuIcon
      fonts:
      - asset: assets/fonts/MenuIcon.ttf

    - family:  IconMenuLain
      fonts:
        - asset: assets/fonts/IconMenuLain.ttf

    - family:  FloatIcon
      fonts:
        - asset: assets/fonts/FloatIcon.ttf

    - family:  No_profile_picture
      fonts:
        - asset: assets/fonts/No_profile_picture.ttf

    - family:  MenuLainIcon
      fonts:
        - asset: assets/fonts/MenuLainIcon.ttf

    - family:  CreateAccount
      fonts:
        - asset: assets/fonts/CreateAccount.ttf

  assets:
    - assets/
    - assets/backgrounds/
    - assets/icon/
