name: flutter_jaring_ummat
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.12.0
  charts_flutter: ^0.6.0
  http: ^0.12.0+1
  shared_preferences: ^0.5.1+2
  image_picker: ^0.5.0+9
  image_cropper: ^1.0.0
  cached_network_image: ^0.8.0
  flutter_spinkit: ^3.1.0
  chewie:
  video_player: ^0.10.0+2
  percent_indicator: "^1.0.16"
  draggable_scrollbar: ^0.0.4
  font_awesome_flutter: ^8.4.0
  mailer: ^2.3.0
  otp: ^1.0.1
  toast: ^0.1.4
  flutter_fab_dialer: ^0.1.1
  bottom_sheet_stateful: ^0.1.1
  dio:
  path_provider:
  timeago: ^2.0.14
  flutter_money_formatter: ^0.8.0
  shimmer: ^1.0.0
  carousel_slider: ^1.3.0
  circular_profile_avatar: ^0.2.0
  intro_slider:
  intro_views_flutter: ^2.6.0
  flutter_image_compress: ^0.4.0
  pie_chart: ^0.9.0
  scoped_model: ^1.0.1
  dots_indicator: ^0.0.5
  file_cache: ^0.1.2
  rubber: ^0.3.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ic_launcher/res/mipmap-xxxhdpi/ic_launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family:  CustomFonts 
      fonts:
        - asset: assets/fonts/custom_icons.ttf
        
    - family:  IconCustom 
      fonts:
        - asset: assets/fonts/IconCustom.ttf

    - family:  HeaderCustom 
      fonts:
        - asset: assets/fonts/HeaderCustom.ttf
     
    - family:  AppBarCustom
      fonts:
        - asset: assets/fonts/AppBarCustom.ttf

    - family:  NavbarCustom
      fonts:
        - asset: assets/fonts/NavbarCustom.ttf

    - family:  IconBaru
      fonts:
      - asset: assets/fonts/IconBaru.ttf

    - family:  MenuIcon
      fonts:
      - asset: assets/fonts/MenuIcon.ttf

    - family:  IconMenuLain
      fonts:
        - asset: assets/fonts/IconMenuLain.ttf

    - family:  FloatIcon
      fonts:
        - asset: assets/fonts/FloatIcon.ttf

    - family:  No_profile_picture
      fonts:
        - asset: assets/fonts/No_profile_picture.ttf

    - family:  MenuLainIcon
      fonts:
        - asset: assets/fonts/MenuLainIcon.ttf

    - family:  CreateAccount
      fonts:
        - asset: assets/fonts/CreateAccount.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/backgrounds/
    - assets/users/
    - assets/icon/

  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
