/// Flutter icons CreateAccount
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CreateAccount
///      fonts:
///       - asset: fonts/CreateAccount.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CreateAccount {
  CreateAccount._();

  static const _kFontFam = 'CreateAccount';

  static const IconData change_password = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData checklist = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData close_dialog = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData create_account_step_1 = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData create_account_step_2 = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData create_account_step_3 = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData delete = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData edit_confirm_password = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData edit_email = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData edit_name = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData edit_password = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData edit_phone = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData empty_profile_picture = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData history = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData forgot_password = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData infaq = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData jaring_ummat_new_logo = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData otp_email = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData setting_2 = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData show_password_active = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData show_password_inactive = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData upload = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData wakaf = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData zakat = const IconData(0xe819, fontFamily: _kFontFam);
}
