/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class CustomFonts {
  CustomFonts._();

  static const _kFontFam = 'CustomFonts';

  static const IconData heart = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData heart_empty = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData chat_bubble_outline = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData bookmark = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData newspaper = const IconData(0xf4f0, fontFamily: _kFontFam);
}
