/// Flutter icons FloatIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FloatIcon
///      fonts:
///       - asset: fonts/FloatIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FloatIcon {
  FloatIcon._();

  static const _kFontFam = 'FloatIcon';

  static const IconData next = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData back = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData add_donation_zakat_etc = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData close_floating = const IconData(0xe803, fontFamily: _kFontFam);
}
