/// Flutter icons HeaderCustom
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HeaderCustom
///      fonts:
///       - asset: fonts/HeaderCustom.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HeaderCustom {
  HeaderCustom._();

  static const _kFontFam = 'HeaderCustom';

  static const IconData ic_news = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData ic_comment_inactive = const IconData(0xe801, fontFamily: _kFontFam);
}
