/// Flutter icons IconMenuLain
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconMenuLain
///      fonts:
///       - asset: fonts/IconMenuLain.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
///
import 'package:flutter/widgets.dart';

class IconMenuLain {
  IconMenuLain._();

  static const _kFontFam = 'IconMenuLain';

  static const IconData calculator = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData shop = const IconData(0xe801, fontFamily: _kFontFam);
}
