/// Flutter icons IconCustom
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconCustom
///      fonts:
///       - asset: fonts/IconCustom.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconCustom {
  IconCustom._();

  static const _kFontFam = 'IconCustom';

  static const IconData bottom_menu_home = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData bottom_menu_inbox = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData bottom_menu_others = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData bottom_menu_portfolio = const IconData(0xe803, fontFamily: _kFontFam);
}
