/// Flutter icons IconBaru
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconBaru
///      fonts:
///       - asset: fonts/IconBaru.ttf
///
/// 
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
///
import 'package:flutter/widgets.dart';

class IconBaru {
  IconBaru._();

  static const _kFontFam = 'IconBaru';

  static const IconData upload = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData add_donation_zakat_etc = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData app_setting = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData badge_member = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData chat = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData close_floating = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData donation_small = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData hide_identity = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData infaq_small = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData reward_point = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData scan_qr = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData shodaqoh_small = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData wakaf_small = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData wallet = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData zakat_small = const IconData(0xe80e, fontFamily: _kFontFam);
}
