/// Flutter icons MenuIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MenuIcon
///      fonts:
///       - asset: fonts/MenuIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MenuIcon {
  MenuIcon._();

  static const _kFontFam = 'MenuIcon';

  static const IconData badge_member_menu = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData notif_chat = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData notif_news = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData notif_reward_point = const IconData(0xe803, fontFamily: _kFontFam);
}
