/// Flutter icons MenuLainIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MenuLainIcon
///      fonts:
///       - asset: fonts/MenuLainIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MenuLainIcon {
  MenuLainIcon._();

  static const _kFontFam = 'MenuLainIcon';

  static const IconData app_setting = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData badge_member_menu = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData calculator_zakat = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData merchant_amal = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData redeem_point = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData saved_donation = const IconData(0xe805, fontFamily: _kFontFam);
}
