/// Flutter icons NavbarCustom
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NavbarCustom
///      fonts:
///       - asset: fonts/NavbarCustom.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NavbarCustom {
  NavbarCustom._();

  static const _kFontFam = 'NavbarCustom';

  static const IconData nav_home_active = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData nav_home_inactive = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData nav_inbox_active = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData nav_inbox_inactive = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData nav_othersmenu_active = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData nav_othersmenu_inactive = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData nav_portfolio_active = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData nav_portfolio_inactive = const IconData(0xe807, fontFamily: _kFontFam);
}