/// Flutter icons No_profile_picture
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  No_profile_picture
///      fonts:
///       - asset: fonts/No_profile_picture.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class No_profile_picture {
  No_profile_picture._();

  static const _kFontFam = 'No_profile_picture';

  static const IconData empty_profile_picture = const IconData(0xe800, fontFamily: _kFontFam);
}
