// USER DETAILS PREFERENCES

const ACCESS_TOKEN_KEY = 'ACCESS_TOKEN';
const EMAIL_KEY = 'EMAIL';
const FULLNAME_KEY = 'FULLNAME';
const USER_ID_KEY = 'USERID';
const CONTACT_KEY = 'CONTACT';
const PROFILE_PICTURE_KEY = 'PROFILEPICTURE';
const PROFILE_FACEBOOK_KEY = 'PROFILEFACEBOOK';


const LEMABAGA_AMAL_ID = 'LEMBAGAAMALID';
const LOKASI_AMAL = 'LOKASIAMAL';
const TEMPAT_LAHIR = 'TEMPATLAHIR';
const ALAMAT_LAHIR = 'ALAMATLAHIR';
const TGL_LAHIR = 'TGLLAHIR';

const FILTER_PROGRAM_AMAL = 'FILTERPROGRAMAMAL';

const CURRENT_LOCATION_CITY = 'KOTASEKARANG';
const CURRENT_LOCATION_PROVINSI = 'PROVINSISEKARANG';

// LINKEDIN CONFIG

const linkedInRedirectURI = 'https://api.linkedin.com/v2/';
const linkedInClientID = '81vfnbt57g6p6q';
const linkedInClientSecret = 'QOzI7o0ZTBAF8hr7';