// USER DETAILS PREFERENCES

const ACCESS_TOKEN_KEY = 'ACCESS_TOKEN';
const EMAIL_KEY = 'EMAIL';

const FULLNAME_KEY = 'FULLNAME';
const USER_ID_KEY = 'USERID';
const CONTACT_KEY = 'CONTACT';
const PROFILE_PICTURE_KEY = 'PROFILEPICTURE';

const INTRO_SLIDER_KEY = 'INTRO_SLIDER';