/// Flutter icons ActiveIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ActiveIcon
///      fonts:
///       - asset: fonts/ActiveIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ActiveIcon {
  ActiveIcon._();

  static const _kFontFam = 'ActiveIcon';

  static const IconData love_active_3x = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData save_active_3x = const IconData(0xe801, fontFamily: _kFontFam);
}
