/// Flutter icons AllInOneIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AllInOneIcon
///      fonts:
///       - asset: fonts/AllInOneIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AllInOneIcon {
  AllInOneIcon._();

  static const _kFontFam = 'AllInOneIcon';

  static const IconData account_following_3x = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData add_chat_3x = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData add_picture_camera_3x = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData add_picture_gallery_3x = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData add_story_3x = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData administration_3x = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData amount_action_3x = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData ask_jejaring_3x = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData back_big_3x = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData back_small_2x = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData backspace_2x = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData balance_2x = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData change_3x = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData chat_3x = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData check_small_2x = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData checklist_2x = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData clear_search_history_3x = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData close_2x = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData close_big_3x = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData comment_3x = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData detail_2x = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData donation_3x = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData copy_link_5x = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData create_galang_amal_3x = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData deadline_3x = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData delete_3x = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData dropdown_2x = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData edit_2x = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData edittext_another_salary_3x = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData edittext_birtdate_3x = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData donation_cancel_3x = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData drop_current_location_3x = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData edittext_gold_3x = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData edittext_loan_3x = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData edittext_monthly_salary_3x = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData edittext_name_3x = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData edittext_nominal_3x = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData edittext_option_3x = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData edittext_people_3x = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData edittext_phone_3x = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData edittext_price_rice_3x = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData edittext_property_3x = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData edittext_savings_3x = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData faq_3x = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData empty_pp_big_12x = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData flash_off_3x = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData flash_on_3x = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData following_3x = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData full_screen_3x = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData hide_identity_2x = const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData indicator_1per3_3x = const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData indicator_2per3_3x = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData indicator_3per3_3x = const IconData(0xe834, fontFamily: _kFontFam);
  static const IconData love_3x = const IconData(0xe835, fontFamily: _kFontFam);
  static const IconData mark_as_read_3x = const IconData(0xe836, fontFamily: _kFontFam);
  static const IconData location_inactive_3x = const IconData(0xe837, fontFamily: _kFontFam);
  static const IconData infaq_3x = const IconData(0xe838, fontFamily: _kFontFam);
  static const IconData information_3x = const IconData(0xe839, fontFamily: _kFontFam);
  static const IconData nav_explore_active_3x = const IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData nav_explore_inactive_3x = const IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData nav_home_active_3x = const IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData nav_home_inactive_3x = const IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData nav_inbox_3x = const IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData nav_inbox_active_3x = const IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData nav_merchant_3x = const IconData(0xe840, fontFamily: _kFontFam);
  static const IconData nav_others_3x = const IconData(0xe841, fontFamily: _kFontFam);
  static const IconData nav_others_active_3x = const IconData(0xe842, fontFamily: _kFontFam);
  static const IconData nav_portfolio_3x = const IconData(0xe843, fontFamily: _kFontFam);
  static const IconData nav_portfolio_active_3x = const IconData(0xe844, fontFamily: _kFontFam);
  static const IconData nav_scan_3x = const IconData(0xe845, fontFamily: _kFontFam);
  static const IconData news_3x = const IconData(0xe846, fontFamily: _kFontFam);
  static const IconData next_big_3x = const IconData(0xe847, fontFamily: _kFontFam);
  static const IconData payment_done_3x = const IconData(0xe848, fontFamily: _kFontFam);
  static const IconData on_process_3x = const IconData(0xe849, fontFamily: _kFontFam);
  static const IconData next_small_2x = const IconData(0xe84a, fontFamily: _kFontFam);
  static const IconData play_4x = const IconData(0xe84b, fontFamily: _kFontFam);
  static const IconData point_2x = const IconData(0xe84c, fontFamily: _kFontFam);
  static const IconData refresh_2x = const IconData(0xe84d, fontFamily: _kFontFam);
  static const IconData reply_3x = const IconData(0xe84e, fontFamily: _kFontFam);
  static const IconData save_3x = const IconData(0xe84f, fontFamily: _kFontFam);
  static const IconData save_active_3x = const IconData(0xe850, fontFamily: _kFontFam);
  static const IconData saved_galang_amal_3x = const IconData(0xe851, fontFamily: _kFontFam);
  static const IconData search_big_3x = const IconData(0xe852, fontFamily: _kFontFam);
  static const IconData search_small_2x = const IconData(0xe853, fontFamily: _kFontFam);
  static const IconData send_3x = const IconData(0xe854, fontFamily: _kFontFam);
  static const IconData setting_app_3x = const IconData(0xe855, fontFamily: _kFontFam);
  static const IconData share_3x = const IconData(0xe856, fontFamily: _kFontFam);
  static const IconData show_identity_2x = const IconData(0xe857, fontFamily: _kFontFam);
  static const IconData sodaqoh_3x = const IconData(0xe858, fontFamily: _kFontFam);
  static const IconData sort_3x = const IconData(0xe859, fontFamily: _kFontFam);
  static const IconData sound_on_3x = const IconData(0xe85a, fontFamily: _kFontFam);
  static const IconData t_c_3x = const IconData(0xe85b, fontFamily: _kFontFam);
  static const IconData twitter_6x = const IconData(0xe85c, fontFamily: _kFontFam);
  static const IconData update_2x = const IconData(0xe85d, fontFamily: _kFontFam);
  static const IconData upload_2x = const IconData(0xe85e, fontFamily: _kFontFam);
  static const IconData wakaf_3x = const IconData(0xe85f, fontFamily: _kFontFam);
  static const IconData wallet_big_3x = const IconData(0xe860, fontFamily: _kFontFam);
  static const IconData whatsapp_5x = const IconData(0xe861, fontFamily: _kFontFam);
  static const IconData zakat_3x = const IconData(0xe862, fontFamily: _kFontFam);
  static const IconData zakat_calculator_3x = const IconData(0xe863, fontFamily: _kFontFam);
}
