/// Flutter icons AppBarIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppBarIcon
///      fonts:
///       - asset: fonts/AppBarIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppBarIcon {
  AppBarIcon._();

  static const _kFontFam = 'AppBarIcon';

  static const IconData location_active = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData location_inactive = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData setting = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData title_jaring_ummat_original = const IconData(0xe804, fontFamily: _kFontFam);
}
