/// Flutter icons AturAkunIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AturAkunIcon
///      fonts:
///       - asset: fonts/AturAkunIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AturAkunIcon {
  AturAkunIcon._();

  static const _kFontFam = 'AturAkunIcon';

  static const IconData alquran_3x = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData shalat_3x = const IconData(0xe801, fontFamily: _kFontFam);
}
