/// Flutter icons CalculatorOtherIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CalculatorOtherIcon
///      fonts:
///       - asset: fonts/CalculatorOtherIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CalculatorOtherIcon {
  CalculatorOtherIcon._();

  static const _kFontFam = 'CalculatorOtherIcon';

  static const IconData edittext_another_salary_3x = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData edittext_birtdate_3x = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData edittext_gold_3x = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData edittext_loan_3x = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData edittext_monthly_salary_3x = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData edittext_option_3x = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData edittext_people_3x = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData edittext_price_rice_3x = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData edittext_property_3x = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData edittext_savings_3x = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData faq_3x = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData location_inactive_3x = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData t_c_3x = const IconData(0xe80c, fontFamily: _kFontFam);
}
