/// Flutter icons GridMenuTambahanIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GridMenuTambahanIcon
///      fonts:
///       - asset: fonts/GridMenuTambahanIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GridMenuTambahanIcon {
  GridMenuTambahanIcon._();

  static const _kFontFam = 'GridMenuTambahanIcon';

  static const IconData mitra_new = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData news_new = const IconData(0xe801, fontFamily: _kFontFam);
}
