/// Flutter icons GridMenuIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GridMenuIcon
///      fonts:
///       - asset: fonts/GridMenuIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GridMenuIcon {
  GridMenuIcon._();

  static const _kFontFam = 'GridMenuIcon';

  static const IconData donation_new = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData infaq_new = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData wakaf_new = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData zakat_new = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData sodaqoh_new = const IconData(0xe804, fontFamily: _kFontFam);
}
