/// Flutter icons HomePageIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HomePageIcons
///      fonts:
///       - asset: fonts/HomePageIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HomePageIcons {
  HomePageIcons._();

  static const _kFontFam = 'HomePageIcons';

  static const IconData bottom_nav_home_active = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData bottom_nav_home_inactive = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData bottom_nav_inbox_active = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData bottom_nav_inbox_inactive = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData bottom_nav_others_active = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData bottom_nav_others_inactive = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData bottom_nav_portfolio_active = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData bottom_nav_portfolio_inactive = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData bottom_nav_scan = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData chat = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData full_screen = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData sound_on = const IconData(0xe80c, fontFamily: _kFontFam);
}
