/// Flutter icons Navigation
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Navigation
///      fonts:
///       - asset: fonts/Navigation.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Navigation {
  Navigation._();

  static const _kFontFam = 'Navigation';

  static const IconData empty_picture = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData back = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData check = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData close = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData next = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData upload = const IconData(0xe816, fontFamily: _kFontFam);
}
