/// Flutter icons NewIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NewIcon
///      fonts:
///       - asset: fonts/NewIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NewIcon {
  NewIcon._();

  static const _kFontFam = 'NewIcon';

  static const IconData account_following_3x = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData add_chat_3x = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData add_picture_camera_3x = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData add_picture_gallery_3x = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData back_big_3x = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData back_small_2x = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData chat_3x = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData checklist_2x = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData close_2x = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData comment_3x = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData delete_3x = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData edittext_name_3x = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData edittext_phone_3x = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData empty_pp_big_12x = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData full_screen_3x = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData love_3x = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData nav_home_active_3x = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData nav_home_inactive_3x = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData nav_inbox_3x = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData nav_others_3x = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData nav_portfolio_3x = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData nav_scan_3x = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData next_big_3x = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData next_small_2x = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData refresh_2x = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData save_3x = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData search_big_3x = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData search_small_2x = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData send_3x = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData share_3x = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData sort_3x = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData sound_on_3x = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData update_2x = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData upload_2x = const IconData(0xe821, fontFamily: _kFontFam);
}
