/// Flutter icons ProfileInboxIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ProfileInboxIcon
///      fonts:
///       - asset: fonts/ProfileInboxIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ProfileInboxIcon {
  ProfileInboxIcon._();

  static const _kFontFam = 'ProfileInboxIcon';

  static const IconData administration_3x = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData balance_2x = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData change_3x = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData check_small_2x = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData donation_3x = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData edit_2x = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData faq_3x = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData infaq_3x = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData mark_as_read_3x = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData nav_inbox_active_3x = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData nav_others_active_3x = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData nav_portfolio_active_3x = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData news_3x = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData play_4x = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData point_2x = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData reply_3x = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData save_active_3x = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData saved_galang_amal_3x = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData setting_app_3x = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData sodaqoh_3x = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData twitter_6x = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData wakaf_3x = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData zakat_3x = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData zakat_calculator_3x = const IconData(0xe817, fontFamily: _kFontFam);
}
