/// Flutter icons SosialMedia
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SosialMedia
///      fonts:
///       - asset: fonts/SosialMedia.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SosialMedia {
  SosialMedia._();

  static const _kFontFam = 'SosialMedia';

  static const IconData facebook = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData google = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData linkedin = const IconData(0xe80f, fontFamily: _kFontFam);
}
